import java.io.PrintStream;

// This interface describes the functions that can be given to the exhaustive search function
// to get different values and statistics
public interface ExhaustiveSearchReducer<T> {
	// This function must take two values and combine them into one without preference for order
	public T reduce(T first, T second);
	
	// This function must return the appropriate value from the given grid
	public T getValue(Grid grid);
	
	// This function must return the identity value for the above reduction
	public T initialValue();
	
	// This function must return a string displaying the values generated by the exhaustive search
	public void display(T values, int numSteps, int alg, PrintStream ps);
}
